### ISSUE TITLE
Server issue on Windows Server 2019 Machine

### ISSUE THREAD

**Issue by LiveGobe** [MenY-dev/StarfallAfterlife#2]
I'm trying to host a Starfall server on my Windows Server 2019 machine. It starts, me and others can connect to it, however, when trying to start a fight with pirates or land on asteroids node the following happens:

1. Splash screen for battle/exploration pops up
2. Camera zooms in
3. Splash screen disappears (Battle/exploration does not start)

And after that I can control my ship again.

On a side note, the game won't start on my server (Pressing play/connect button shows game logo and than closes with no warnings)

P.S. I did install all necessary redistributables on my server.
P.P.S. On my Windows 10 PC everything works perfectly fine

**Comment by MenY-dev** [comment]
This is not a Windows Server issue.
The problem is that on the original servers, battles were launched on a special build of the game, with disabled graphics. But the server build of the game is not available along with the development team itself, which is why I have to launch the client build of the game in server mode, but without disabled graphics.

Therefore, a video card with support for at least DirectX10 and Shader Model 4 is required to run the server. All relevant drivers must also be installed. Battles on the server are launched without disabled graphics, but the graphics are very limited, so a powerful video card is not required.

**Comment by LiveGobe** [comment]
Thanks for the answer, I found the solution - I installed Intel graphics for integrated GPU.
